version: "3.9"

services:
  api:
    image: ghcr.io/saleor/saleor:3.20
    container_name: api
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    volumes:
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - DASHBOARD_URL=http://shop.scopal-affairs.com:9000
      - ALLOWED_HOSTS=shop.scopal-affairs.com,saleor-storefront-self.vercel.app

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:latest
    container_name: dashboard
    networks:
      - saleor-backend-tier
    ports:
      - "9000:9000"
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    # This one-off container is used to initially obtain certificates.
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    networks:
      - saleor-backend-tier
    # Run this container manually (or with --rm) when you need to issue a new certificate.

  # certbot-renew:
  #   image: certbot/certbot:latest
  #   container_name: certbot-renew
  #   # This long-running service checks for renewal every 12 hours.
  #   entrypoint: sh -c "while true; do certbot renew --quiet && sleep 12h; done"
  #   volumes:
  #     - certbot-www:/var/www/certbot
  #     - certbot-conf:/etc/letsencrypt
  #   networks:
  #     - saleor-backend-tier
  #   restart: unless-stopped

  db:
    image: library/postgres:15-alpine
    container_name: db
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: library/redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    image: ghcr.io/saleor/saleor:3.20
    container_name: celery
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file:
      - common.env
      - backend.env
    depends_on:
      - redis
    volumes:
      - saleor-media:/app/media

  api-gateway:
    image: nginx:stable-alpine
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - saleor-backend-tier
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the named volume containing certbot data read-only for nginx.
      - certbot-conf:/etc/letsencrypt:ro
      # Persist nginx logs (ensure the host directory exists or change as needed).
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - api
      - dashboard

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
